---
#----------------------------------------
# Node manager Web Player (Windows) service template
# - https://docs.tibco.com/pub/spotfire_server/latest/doc/html/TIB_sfire_server_tsas_admin_help/server/topics/service_configuration_files.html
# - https://docs.tibco.com/pub/spotfire_server/latest/doc/html/TIB_sfire_server_tsas_admin_help/server/topics/manually_editing_the_service_configuration_files.html
# - https://docs.tibco.com/pub/spotfire_server/latest/doc/html/TIB_sfire_server_tsas_admin_help/server/topics/automatically_installing_services_and_instances.html
#----------------------------------------

# https://docs.ansible.com/ansible/2.10/collections/ansible/builtin/stat_module.html
- name: Windows | Check local 'default.json' file checksum (service template)
  stat:
    path: "{{ role_path }}/files/default_service.json"
    checksum_algorithm: sha1
  delegate_to: localhost
  register: local_service_definition

# https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_stat_module.html
- name: Windows | Check remote 'default.bak' file exists and its checksum (the service has been installed)
  ansible.windows.win_stat:
    path: 'C:\tibco\tsnm\{{ tss_version }}\nm\config\default.bak'
    checksum_algorithm: sha1
#  failed_when: remote_files.stat.checksum != item.stat.checksum
  register: remote_service_file_backup

- name: Windows | Adding Web Player service from a template (only if no service has been installed or service definition cksum differs)
  win_copy:
    src: files/default_service.json
    dest: 'C:\tibco\tsnm\{{ tss_version }}\nm\config\default.conf'
  when: remote_service_file_backup.stat.exists == false or remote_service_file_backup.stat.checksum != local_service_definition.stat.checksum
