---
#----------------------------------------
# Web Player (Linux) package install
#----------------------------------------

#- name: Get first tss server hostname
#  debug:
#    msg: "{{ hostvars[groups['tss_servers'][0]]['name'] | regex_replace('^(.*)-vm$', '\\1') }}"
#  register: tss_hostname

- set_fact:
    tss_hostname: "{{ hostvars[groups['tss_servers'][0]]['name'] | regex_replace('^(.*)-vm$', '\\1') }}"

- name: Show tss_hostname
  debug:
    msg: "{{ tss_hostname }}"

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/service_facts_module.html
# Making install idempotent
- name: Linux | Check if the Spotfire node manager service is installed & started
  service:
    name: tsnm-{{ tss_version }}
    state: started
  register: nm_service
  changed_when: false # this is just a check, we do not want to show as changed
  ignore_errors: yes

#- debug:
#    msg: "Linux | Is the Node manager service already installed? '{{ nm_service }}'"

- name: Linux | Verify Spotfire node manager service status
  set_fact:
    nm_service_exists: "{{ false if (nm_service.failed == true) else true }}"

- debug:
    msg: "Linux | Is the Spotfire node manager service already installed? '{{ nm_service_exists }}'"

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html
- name: Linux | Copy Spotfire node manager linux package (tsnm-{{ tss_version }}.x86_64.rpm)
  copy:
    src: "{{ spotfire_local_sw_repo }}/tsnm-{{ tss_version }}.x86_64.rpm"
    dest: "{{ spotfire_remote_sw_repo }}"
    owner: spotfire
    group: spotfire
    mode: '0644'
  tags: cp_package
  when: nm_service_exists is false

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/yum_module.html
- name: Linux | RedHat | Install Spotfire node manager (tsnm) package
  yum:
    name: "{{ spotfire_remote_sw_repo }}/tsnm-{{ tss_version }}.x86_64.rpm"
    state: present
  tags: tsnm_install
  become: true
  when: nm_service_exists is false and ansible_distribution_file_variety == "RedHat"

# https://docs.ansible.com/ansible/latest/collections/community/general/zypper_module.html
- name: Linux | SUSE | Install Spotfire node manager (tsnm) package
  zypper:
    name: "{{ spotfire_remote_sw_repo }}/tsnm-{{ tss_version }}.x86_64.rpm"
    state: present
    disable_gpg_check: yes
  tags: tsnm_install
  become: true
  when: nm_service_exists is false and ansible_distribution_file_variety == "SUSE"

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/command_module.html
- name: Linux | Run Spotfire node manager configure script
#  command: configure -m <NODEMANAGER_REGISTRATION_PORT> -c <NODEMANAGER_COMMUNICATION_PORT> -s <SERVER_NAME> -r <SERVER_BACKEND_REGISTRATION_PORT> -b <SERVER_BACKEND_COMMUNICATION_PORT> -n <NODEMANAGER_HOST_NAMES>
#  command: configure -m 9080 -c 9443 -s $TSS_HOSTNAME -r 9080 -b 9443 -n $NM_HOSTNAME
  command: /opt/tibco/tsnm/{{ tss_version }}/configure -s {{ tss_hostname }} -n {{ ansible_hostname }}
  become: true
  become_user: spotfire
  when: nm_service_exists is false
