---
- name: Set facts tss_ip_address and tsnm_ip_address (Azure)
  ansible.builtin.include_tasks: hosts_azure.yml
  when: target_environment == 'Azure'

- name: Set facts tss_ip_address and tsnm_ip_address (AWS)
  ansible.builtin.include_tasks: hosts_aws.yml
  when: target_environment == 'AWS'

- name: Set facts tss_ip_address and tsnm_ip_address (GCP)
  ansible.builtin.include_tasks: hosts_gcp.yml
  when: target_environment == 'GCP'

# Include OS specific tasks
- name: Install TIBCO Spotfire node manager on Linux (.tar.gz for Debian)
  ansible.builtin.include_tasks: linux-targz.yml
  when: ansible_distribution_file_variety is defined and (ansible_distribution_file_variety == "Debian")
- name: Install TIBCO Spotfire node manager on Linux (.rpm for RHEL or SUSE)
  ansible.builtin.include_tasks: linux-rpm.yml
  when: ansible_distribution_file_variety is defined and (ansible_distribution_file_variety == "RedHat" or ansible_distribution_file_variety == "SUSE")
- name: Install TIBCO Spotfire node manager on Windows (.exe)
  ansible.builtin.include_tasks: windows.yml
  when: ansible_os_family == "Windows"
