---
#----------------------------------------
# Spotfire Server service
# - https://docs.tibco.com/pub/spotfire_server/latest/doc/html/TIB_sfire_server_tsas_admin_help/server/topics/starting_or_stopping_spotfire_server_(linux).html
#----------------------------------------

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/systemd_module.html
- name: Restart Spotfire Server (sfs) service to apply config changes
  ansible.builtin.systemd:
    name: spotfireserver-{{ spotfire_version }}
    enabled: true
    state: restarted
  tags: sfs_service

#- debug:
#    msg: Restarting Spotfire Server (sfs) service {{ inventory_hostname }} to apply config changes
#  notify: restart sfs

#- name: Flush handlers
#  meta: flush_handlers
