#----------------------------------------
# Install libgdiplus from rpm (Debian)
#----------------------------------------

# https://docs.microsoft.com/en-us/dotnet/core/install/linux-debian
- name: Linux | Debian | Install Microsoft .NET package repository
  ansible.builtin.apt:
    deb: https://packages.microsoft.com/config/debian/11/packages-microsoft-prod.deb
    state: present
    allow_unauthenticated: true
  become: true
  when: ansible_distribution_file_variety == "Debian"

- name: Install apt-transport-https
  ansible.builtin.apt:
    name: apt-transport-https
    state: present
    update_cache: true
  become: true
  when: ansible_distribution_file_variety == "Debian"

- name: Install Microsoft .NET
  ansible.builtin.apt:
    name: aspnetcore-runtime-6.0
    state: present
    update_cache: true
  become: true
  when: ansible_distribution_file_variety == "Debian"

- name: Install Spotfire package dependencies
  ansible.builtin.apt:
    name:
      - libcairo2
      - libexif12
      - libfontconfig1
      - libgif7
      - libglib2.0-0
      - libharfbuzz0b
      - libjpeg62-turbo
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpng16-16
      - libtiff5
      - libx11-6
      - libxcomposite1
      - libasound2
      - libnss3
      - libatk-bridge2.0-0
      - libgbm1
      - libcups2
      - libxdamage1
      - libxrandr2
      - libxkbcommon0
      - xvfb
      - xauth
      - unixodbc
    state: present
  become: true
  when: ansible_distribution_file_variety == "Debian"

- name: Install common font packages
  ansible.builtin.apt:
    name:
      - fonts-arphic-ukai
      - fonts-arphic-uming
      - fonts-ipafont-mincho
      - fonts-ipafont-gothic
      - fonts-liberation
      - fonts-unfonts-core
      - fonts-roboto
    state: present
  become: true
  when: ansible_distribution_file_variety == "Debian"
