# Include OS specific tasks
- name: Install TIBCO Spotfire Web Player dependencies on RHEL
  ansible.builtin.include_tasks: deps_rhel.yml
  when: ansible_distribution_file_variety is defined and (ansible_distribution_file_variety == "RedHat")

- name: Install TIBCO Spotfire Web Player dependencies on SUSE
  ansible.builtin.include_tasks: deps_suse.yml
  when: ansible_distribution_file_variety is defined and (ansible_distribution_file_variety == "SUSE")

- name: Install TIBCO Spotfire Web Player dependencies on Debian
  ansible.builtin.include_tasks: deps_debian.yml
  when: ansible_distribution_file_variety is defined and (ansible_distribution_file_variety == "Debian")
