---
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/group_module.html
- name: Create group "spotfire"
  ansible.builtin.group:
    name: spotfire
    state: present
    gid: 1010
  become: true

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/user_module.html
- name: Create user 'spotfire'
  ansible.builtin.user:
    name: spotfire
    comment: Spotfire user
#    uid: 1010
    group: spotfire
    shell: /bin/bash
    state: present
  become: true

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html
- name: Create directory for software repo
  ansible.builtin.file:
    #path: /var/local/spotfire/swrepo
    path: "{{ spotfire_remote_sw_repo }}"
    owner: spotfire
    group: spotfire
    recurse: true
    state: directory
  tags: swrepo
  become: true
