---
# Include OS specific tasks
- ansible.builtin.include_tasks: linux.yml
#  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"
  when: ansible_distribution_file_variety is defined and (ansible_distribution_file_variety == "Debian" or ansible_distribution_file_variety == "RedHat" or ansible_distribution_file_variety == "SUSE")
#- ansible.builtin.include_tasks: windows.yml
#  when: ansible_os_family == "Windows"
