---
#----------------------------------------
# Web Player role (Windows) service
#----------------------------------------

# https://github.com/ansible-collections/ansible.windows/blob/main/docs/ansible.windows.win_service_module.rst
# Requires ansible.windows collection
# Install:
#  $ ansible-galaxy collection install ansible.windows
- name: Windows | Set the Node manager service to automatic start on boot
  win_service:
    name: TIBCO Spotfire Node Manager {{ tss_version }}
    start_mode: auto

- name: Windows | Start the Node manager service
  win_service:
    name: TIBCO Spotfire Node Manager {{ tss_version }}
    state: restarted
