# Include OS specific tasks
- name: Install Spotfire Web Player dependencies on RHEL
  ansible.builtin.include_tasks: deps_rhel.yml
  when: ansible_distribution_file_variety is defined and (ansible_distribution_file_variety == "RedHat")

- name: Install Spotfire Web Player dependencies on SUSE
  ansible.builtin.include_tasks: deps_suse.yml
  when: ansible_distribution_file_variety is defined and (ansible_distribution_file_variety == "SUSE")

- name: Install Spotfire Web Player dependencies on Debian 11
  ansible.builtin.include_tasks: deps_debian_11.yml
  when: ansible_distribution_file_variety is defined and (ansible_distribution_file_variety == "Debian") and ansible_distribution_major_version == "11"

- name: Install Spotfire Web Player dependencies on Debian 12
  ansible.builtin.include_tasks: deps_debian_12.yml
  when: ansible_distribution_file_variety is defined and (ansible_distribution_file_variety == "Debian") and ansible_distribution_major_version == "12"
