# SSH connection
ansible_user: '{{ sfs_user }}'
#ansible_password: '{{ sfs_password }}'
#ansible_sudo_pass: '{{ sfs_password }}'
#ansible_ssh_private_key_file: '{{ ssh_private_key_file }}'

#ansible_ssh_common_args: '-o "ProxyCommand ssh -W %h:%p {{ jumphost_user }}@{{ jumphost_host }}" -i ~/.ssh/id_rsa {{ ssh_common_args }}'
ansible_ssh_common_args: '{{ ssh_common_args }} -o ControlMaster=no -o "ProxyCommand ssh -W %h:%p {{ jumphost_user }}@{{ jumphost_host }} -i {{ ssh_private_key_file }} {{ ssh_common_args }}"'