---
#----------------------------------------
# Node manager Web Player (Linux) service template
# - https://docs.tibco.com/pub/spotfire_server/latest/doc/html/TIB_sfire_server_tsas_admin_help/server/topics/service_configuration_files.html
# - https://docs.tibco.com/pub/spotfire_server/latest/doc/html/TIB_sfire_server_tsas_admin_help/server/topics/manually_editing_the_service_configuration_files.html
# - https://docs.tibco.com/pub/spotfire_server/latest/doc/html/TIB_sfire_server_tsas_admin_help/server/topics/automatically_installing_services_and_instances.html
#----------------------------------------

# https://docs.ansible.com/ansible/2.10/collections/ansible/builtin/stat_module.html
- name: Linux | Check local 'default.json' file checksum (service template)
  ansible.builtin.stat:
    path: "{{ role_path }}/files/default_service.json"
    checksum_algorithm: sha1
  delegate_to: localhost
  become: false
  register: local_service_definition

- name: Linux | Check remote 'default.bak' file exists and its checksum (the service has been installed)
  ansible.builtin.stat:
    path: '/opt/spotfire/spotfirenodemanager/{{ spotfire_version }}/nm/config/default.conf'
    checksum_algorithm: sha1
#  failed_when: remote_files.stat.checksum != item.stat.checksum
  register: remote_service_file_backup

# https://docs.tibco.com/pub/spotfire_server/latest/doc/html/TIB_sfire_server_tsas_admin_help/server/topics/automatically_installing_services_and_instances.html
- name: Linux | Adding Web Player service from a template (only if no service has been installed or service definition cksum differs)
  ansible.builtin.copy:
    src: files/default_service.json
    dest: '/opt/spotfire/spotfirenodemanager/{{ spotfire_version }}/nm/config/default.conf'
    owner: spotfire
    group: spotfire
    mode: '0644'
  when: not remote_service_file_backup.stat.exists or remote_service_file_backup.stat.checksum != local_service_definition.stat.checksum
