# Include OS specific tasks
- name: Install Spotfire Web Player on Linux (tar.gz)
  ansible.builtin.include_tasks: linux.yml
  when: ansible_distribution_file_variety is defined and (ansible_distribution_file_variety == "Debian" or ansible_distribution_file_variety == "RedHat" or ansible_distribution_file_variety == "SUSE")
- name: Install Spotfire Web Player on Windows
  ansible.builtin.include_tasks: windows.yml
  when: ansible_os_family == "Windows"
