---
#----------------------------------------
# Spotfire Server package install
# - https://docs.tibco.com/pub/spotfire_server/latest/doc/html/TIB_sfire_server_tsas_admin_help/server/topics/installing_the_spotfire_server_files_(rpm_linux).html
#----------------------------------------
# Include OS specific tasks
#- name: Create Spotfire DB table schemas with scripts
#  ansible.builtin.include_tasks: createdb-scripts.yml
#  when: use_createdb_scripts is defined and (use_createdb_scripts == "true")
- name: Create Spotfire DB table schemas with CLI
  ansible.builtin.include_tasks: createdb-cli.yml
#  when: use_createdb_cli is defined and (use_createdb_cli == "true")
