# initial install

# Create Spotfire DB table schemas
create_db: true
# If we are using cloud service database (currently only tested with Azure database for PostgreSQL)
use_cloud_db: true
# If we want to bootstrap the sfs server (required for initial install or when adding new sfs servers)
sfs_bootstrap: true
# If we want to create the Web Player service from template
create_sfwp_service: true
# Force sdn files deploy (if there is a previous deployment with the same version)
force_sdn_deploy: true
# Force sfnm_service_install (do not skip if already installed)
sfnm_service_reinstall: true

# sfs version
spotfire_version: '14.0.0'
sfs_home: '/opt/spotfire/spotfireserver/{{ spotfire_version }}'

# NOTE: This is an internal fix for getting the Windows service name (variable) using lookup.ini based on the {{ spotfire_version }}
regex: "[`'\"]"
replace: ""
LTS: "{{ lookup('ini', '{{ spotfire_version }} section=sfnm_service_name_win file=config/lookup.ini default=') }}"
sfnm_service_name_win: "Spotfire Node Manager {{ spotfire_version }}{{ LTS|regex_replace(regex, replace) }}"

# location of Spotfire software packages
spotfire_local_sw_repo: ../swrepo/build/{{ spotfire_version }}
# NOTE: Do not remove the ending '/'. It is relevant for the behavior of the ansible copy module
spotfire_remote_sw_repo: /var/local/spotfire/swrepo/

## Spotfire DB
db_type: postgres
db_host: sandbox-postgresql-server.postgres.database.azure.com
db_port: 5432

## Spotfire DB Admin user and password
db_admin_user: dbadmin@sandbox-postgresql-server
db_admin_password: 'ch4ng3Th1sP4ssw0rd!'

# Spotfire Database name, username and password for the Spotfire database.
db_name: sandbox-spotfire-db
# NOTE: For Azure, we use the same user&password for the spotfiredb than for the dbserver
db_user: '{{ db_admin_user }}'
db_password: '{{ db_admin_password }}'

# Spotfire Config tool password
config_tool_password: 'ch4ng3Th1sP4ssw0rd!'

# Spotfire Admin GUI user and password
spotfire_ui_admin_user: admin
spotfire_ui_admin_password: 'ch4ng3Th1sP4ssw0rd!'

# Jumphost credentials
jumphost_user: 'spotfire'
jumphost_password: 'ch4ng3Th1sP4ssw0rd!'

## Spotfire Server credentials
sfs_user: 'spotfire'
sfs_password: 'ch4ng3Th1sP4ssw0rd!'

# Web Player credentials
sfwp_user: 'spotfire'
sfwp_password: 'ch4ng3Th1sP4ssw0rd!'
