---
# Check if sfs service exist to skip install stesp (intelligent+idempotent)

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/service_facts_module.html
- name: Linux | Check if the Spotfire Server service is installed & started
  ansible.builtin.service:
    name: spotfireserver-{{ spotfire_version }}
    state: started
  register: sfs_service
  changed_when: false # this is just a check, we do not want to show as changed
  ignore_errors: true
  tags: sfs_install

- ansible.builtin.debug:
    msg: "Linux | Spotfire Server service details: '{{ sfs_service }}'"
    verbosity: 1
  tags: sfs_install

- name: Linux | Verify Spotfire Serverr service status
  ansible.builtin.set_fact:
    sfs_service_exists: "{{ false if (sfs_service.failed == true) else true }}"
  tags: sfs_install

- ansible.builtin.debug:
    msg: "Linux | Is the Spotfire Server service already installed? '{{ sfs_service_exists }}'"
  tags: sfs_install
