---
# Check if sfnm service exist to skip install stesp (intelligent+idempotent)

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/service_facts_module.html
- name: Linux | Check if the Spotfire node manager service is installed & started
  ansible.builtin.service:
    name: spotfirenodemanager-{{ spotfire_version }}
    state: started
  register: sfnm_service
  changed_when: false # this is just a check, we do not want to show as changed
  ignore_errors: true
  tags: sfnm_install

- ansible.builtin.debug:
    msg: "Linux | Spotfire node manager service details: '{{ sfnm_service }}'"
    verbosity: 1
  tags: sfnm_install

- name: Linux | Verify Spotfire node manager service status
  ansible.builtin.set_fact:
    sfnm_service_exists: "{{ false if (sfnm_service.failed == true) else true }}"
  tags: sfnm_install

- ansible.builtin.debug:
    msg: "Linux | Is the Spotfire node manager service already installed? '{{ sfnm_service_exists }}'"
  tags: sfnm_install
