---
#----------------------------------------
# Spotfire Server service
# - https://docs.tibco.com/pub/spotfire_server/latest/doc/html/TIB_sfire_server_tsas_admin_help/server/topics/starting_or_stopping_spotfire_server_(linux).html
#----------------------------------------

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/systemd_module.html
- name: Start Spotfire Server (sfs) service and set to automatic start on boot
  ansible.builtin.systemd:
    name: spotfireserver-{{ spotfire_version }}
    enabled: true
    state: started
  tags: sfs_service
