---
- name: Deploy Spotfire Server hosts
  hosts: sfs_servers
  remote_user: '{{ sfs_user }}'
  become: true
  roles:
    - common
    - env
    - sfs_install
    - { role: sfdb_createdb, run_once: true }   # NOTE: This runs only on one sfs
    - sfs_bootstrap # NOTE: We throttle this role, so it bootstraps one sfs at a time
    - sfs_service
    - { role: sfs_deploy_sdn, run_once: true }   # NOTE: This runs only on one sfs
    - { role: sfs_autotrust, run_once: true }
    - sfs_service_reload
  environment:
#    SPOTFIRE_HOME: "{{ sfs_home }}"
    SPOTFIRE_VERSION: '{{ spotfire_version }}'
    SPOTFIRE_DB_TYPE: '{{ db_type }}'
    SPOTFIRE_DB_HOST: '{{ db_host }}'
    SPOTFIRE_DB_NAME: '{{ db_name }}'
    SPOTFIRE_DB_ADMIN_USER: '{{ db_admin_user }}'
    SPOTFIRE_DB_ADMIN_PASSWORD: '{{ db_admin_password }}'
    SPOTFIRE_CONFIG_TOOL_PASSWORD: '{{ config_tool_password }}'
    SPOTFIRE_UI_ADMIN_USER: '{{ spotfire_ui_admin_user }}'
    SPOTFIRE_UI_ADMIN_PASSWORD=: '{{ spotfire_ui_admin_password }}'

- name: Deploy Spotfire Web Player hosts
  hosts: sfwp_servers
  remote_user: '{{ sfwp_user }}'
  become: true # works on Windows?
  roles:
    - common
    - sfnm_firewall
    - sfnm_install
    - sfwp_deps
    - { role: sfwp, when: create_sfwp_service }
    - sfnm_service
