---
#----------------------------------------
# Spotfire Server service
# - https://docs.tibco.com/pub/spotfire_server/latest/doc/html/TIB_sfire_server_tsas_admin_help/server/topics/starting_or_stopping_spotfire_server_(linux).html
#----------------------------------------

- name: Restart Spotfire Server (sfs) service
  ansible.builtin.systemd:
    name: spotfireserver-{{ spotfire_version }}
    state: restarted
  listen: "restart sfs"
