---
#----------------------------------------
# Environment variables
#----------------------------------------

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/template_module.html
- name: Copy Spotfire config.env in profile.d
  ansible.builtin.template:
    src: templates/config.env
    dest: /etc/profile.d/spotfire.env
    owner: spotfire
    group: spotfire
    mode: '0600'
  tags: profile
